### ISSUE TITLE
how to grab the screen instead of camera?

### ISSUE THREAD

**Issue by gaming-hacker** [nakajijapan/NKJMultiMovieCaptureView#2]
any hints?

**Comment by nakajijapan** [comment]
Hi, @gaming-hacker.

Sorry for the delay...
You can record video when you are touching screen of camera.
You can stop recording when you finished touching(release the finger).

Is it correct to your question?

**Comment by gaming-hacker** [comment]
Hi,
Thanks for reply.

I was looking to capture a video of the screen if you were playing a game and wanted to save a video of it.  In iOS9 screen capture to video is built in.
